//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_demo_Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease_tb
    {
        public int diseaseID { get; set; }
        public string diseaseName { get; set; }
        public string description { get; set; }
        public string treatment { get; set; }
        public string prfered_drugs { get; set; }
    }
}
