//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_demo_Apps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class community_medicine_dbEntities : DbContext
    {
        public community_medicine_dbEntities()
            : base("name=community_medicine_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<center_tb> center_tb { get; set; }
        public virtual DbSet<disease_tb> disease_tb { get; set; }
        public virtual DbSet<district_tb> district_tb { get; set; }
        public virtual DbSet<doctor_tb> doctor_tb { get; set; }
        public virtual DbSet<medicine_tb> medicine_tb { get; set; }
        public virtual DbSet<patient_tb> patient_tb { get; set; }
        public virtual DbSet<stock_tb> stock_tb { get; set; }
        public virtual DbSet<thana_tb> thana_tb { get; set; }
        public virtual DbSet<total_stock_tb> total_stock_tb { get; set; }
        public virtual DbSet<treatment_tb> treatment_tb { get; set; }
    }
}
