//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_demo_Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_tb
    {
        public int patientID { get; set; }
        public int voterID { get; set; }
        public string patientName { get; set; }
        public string address { get; set; }
        public int age { get; set; }
        public int patientService { get; set; }
    }
}
