//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_demo_Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_stock_tb
    {
        public int totalstockID { get; set; }
        public int centerID { get; set; }
        public string centerName { get; set; }
        public int medicineID { get; set; }
        public string medicineName { get; set; }
        public double stock { get; set; }
    }
}
