//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_demo_Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment_tb
    {
        public int treatmentID { get; set; }
        public int doctorID { get; set; }
        public string doctorName { get; set; }
        public string date { get; set; }
        public int patientID { get; set; }
        public string patientName { get; set; }
        public int centerID { get; set; }
        public string centerName { get; set; }
        public int diseaseID { get; set; }
        public string diseaseName { get; set; }
        public int medicineID { get; set; }
        public string medicineName { get; set; }
        public Nullable<int> dose { get; set; }
        public string timeForTake { get; set; }
        public Nullable<int> quantity { get; set; }
        public string note { get; set; }
        public string observation { get; set; }
    }
}
